---
- name: Install httpd on AlmaLinux, CentOS, and Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Install httpd
      package:
        update_cache: yes
        name: httpd
        state: present
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
