---

- name: deploy httpd server
  hosts: all
  become: yes
  tasks:
  - name: install httpd
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: start & enabled httpd
    service:
      name: httpd
      state: started
      enabled: yes

  - name: copy index.html
    copy:
      src: index.html
      dest: /var/www/html/






#Pour supprimer httpd (apache)
#sudo yum remove httpd