---

- name: install and start tomcat
  hosts: redhat
  become: yes
  tasks:
  
    - name: install tomcat
      yum:
        name: tomcat
        state: present

    - name: start & enabled tomcat
      service:
        name: tomcat
        state: started
        enabled: yes

    - name: copy index.html
      copy:
        src: index.html
        dest: /var/www/html/






#Pour supprimer httpd (apache)
#sudo yum remove httpd
