---
- name: Install Apache Tomcat10 using ansible
  hosts: all
#  remote_user: ubuntu
  become: true
  tasks:
  - name: Install Java
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Install Tomcat
    yum:
      name: tomcat
      state: present
  - name: Start Tomcat
    service:
      name: tomcat
      state: started
      enabled: true