---

- name: install and start http
  hosts: 192.168.33.11
  become: yes
  tasks:
    - name: install 
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: start & enabled httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: copy index.html
      copy:
        src: index.html
        dest: /var/www/html/






