--- 
- name: Install and start Apach httpd and firewall
  hosts: all
  tasks:
    - name: Install httpd and firewall
      package:
        name:
          - httpd
          - firewalld
        state: present
